# Generated by Django 5.2.17 on 2026-09-09 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blob', models.BinaryField()),
                ('criado_em', models.DateTimeField()),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
                ('origem', models.CharField(choices=[('enviada', 'Enviada'), ('recebida', 'Recebida')], max_length=10)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebidas', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['destinatario', '-recebido_em'], name='messenger_m_destina_55da45_idx')],
            },
        ),
    ]
