# Generated by Django 5.2.17 on 2026-09-17 16:06

import hashlib

from django.db import migrations, models


def fill_hashes(apps, schema_editor):
    Message = apps.get_model("messenger", "Message")
    for message in Message.objects.filter(blob_sha256="").only("pk", "blob"):
        Message.objects.filter(pk=message.pk).update(
            blob_sha256=hashlib.sha256(bytes(message.blob)).hexdigest()
        )


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_english_identifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='blob_sha256',
            field=models.CharField(db_index=True, default='', editable=False, max_length=64, verbose_name='hash do conteúdo'),
        ),
        migrations.RunPython(fill_hashes, migrations.RunPython.noop),
    ]
