# Generated by Django 5.2.17 on 2026-09-18 16:07

from django.conf import settings
from django.db import migrations, models


def drop_duplicate_copies(apps, schema_editor):
    Message = apps.get_model("messenger", "Message")
    seen = set()

    for message in Message.objects.order_by("pk").only(
        "pk", "sender", "recipient", "direction", "blob_sha256"
    ):
        copy = (message.sender_id, message.recipient_id, message.direction, message.blob_sha256)
        if copy in seen:
            Message.objects.filter(pk=message.pk).delete()
        else:
            seen.add(copy)


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_key_backup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(drop_duplicate_copies, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('sender', 'recipient', 'direction', 'blob_sha256'), name='message_unique_copy'),
        ),
    ]
